language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

# faster builds on new travis setup not using sudo
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

addons:
  apt:
    sources:
      - gearman-developers
    packages:
      - autoconf
      - pkg-config
      - libzmq3-dev
      - libpgm-5.1-0
      - libgearman-dev
      - gearmand
      - gearman-job-server

services:
  - rabbitmq

install:
  - composer self-update && composer --version
  - composer install --prefer-dist
  - composer require satooshi/php-coveralls:*@dev
  - chmod -R +x tests/data/travis/
  - tests/data/travis/zmq-setup.sh
  - tests/data/travis/gearman-setup.sh
  - tests/data/travis/rabbitmq-setup.sh

script:
  - mkdir -p build/logs
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      vendor/bin/phpunit --verbose --exclude-group php,mq
    else
      vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml --exclude-group hhvm
    fi

after_script:
  - vendor/bin/coveralls -v